### ISSUE TITLE
dcterms:created causes an error.

### ISSUE THREAD

**Issue by lalewis1** [Kurrawong/sparql#6]
> Issue migrated from https://github.com/Kurrawong/tools/issues/73

It seems there is an error with the sparql format utility, for some reason it can not format a sparql query with dcterms:created in it

__steps to reproduce__

    navigate to https://tools.dev.kurrawong.ai/sparql-validate

    insert the query

    ```sparql
    prefix dcterms: <http://purl.org/dc/terms/>
    select *
    where {
        ?s dcterms:created ?o .
    }
    ```

    click format

> Note: if you click validate it will validate successfully.

> Note: if you use another predicate like dcterms:creator then it will format successfully

__expected outcome__
A nicely formatted query is returned

__actual outcome__
400 response with error message

```
No terminal matches 's' in the current parser context, at line 2 col 1

select *
^
Expected one of: 
	* __ANON_83
	* __ANON_82
	* BASE
	* __ANON_89
	* __ANON_92
	* __ANON_88
	* __ANON_85
	* __ANON_87
	* __ANON_93
	* __ANON_84
	* PREFIX
	* __ANON_90
```

**Comment by edmondchuc** [comment]
https://tools.dev.kurrawong.ai/sparql-validate uses the format_string utility function which implements a naive check as to whether the query is a SPARQL 1.1 query or a SPARQL 1.1 Update query when `parser_type` is set to `guess`.

```sparql
prefix dcterms: <http://purl.org/dc/terms/>
select *
where {
    ?s dcterms:created ?o .
}
```

Because the above query contains the substring `create`, it is wrongly guessing that it's a SPARQL 1.1 Update query, and `select *` is not valid.

The SPARQL format utility function should try and parse first with the `sparql` parser and if that fails, try and parse with `sparql_update`.

I also noticed there is incomplete functionality with the SPARQL validate functionality in the tools website. The SPARQL validate functionality really should require the user to choose whether they're validating a SPARQL 1.1 query or a SPARQL 1.1 Update query. It currently fails when a SPARQL 1.1 Update query is provided.

```sparql
insert data {
 <urn:1> <urn:2> <urn:3>
}
```
